routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\SuggestionController;
use App\Http\Controllers\SubmissionsController;
use App\Http\Controllers\ActiveLocalGovtController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/login', function () {
    header('Location:/admin');
    exit();
})->name('login');


Route::group(['prefix' => 'admin'], function () {
    Route::get('/get_submissions', [SubmissionsController::class, 'get_submissions'])->name('get_submissions');
    Route::get('/get_asset_data', [SubmissionsController::class, 'get_asset_data'])->name('get_asset_data');
    Route::get('/admin_dashboard', [DashboardController::class, 'admin_dashboard'])->name('admin_dashboard');
    Route::get('/supervisor_dashboard', [DashboardController::class, 'supervisor_dashboard'])->name('supervisor_dashboard');
    Route::get('/active_local_govt', [ActiveLocalGovtController::class, 'index'])->name('active_local_govt');

    // Route::get('/admin_dashboard', function () {
    //     return view('admin_dashboard');
    // });
    // Route::get('/supervisor_dashboard', function () {
    //     return view('supervisor_dashboard');
    // });
});

Route::resource('suggestions', SuggestionController::class);

Route::get('/', [LanguageController::class, 'index'])->name('home');
Route::get('lan-change', [LanguageController::class, 'langChange'])->name('lan.change');

resources/views/active_local_govt.blade.php
@extends('crudbooster::admin_template')
@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Surveyed Local Governments</h3>
                </div>

                <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Code</th>
                                <th>Local Government</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($local_govt as $row)
                                <tr>
                                    <td>{{ $row->local_govt_code }}</td>
                                    <td>{{ $row->local_govt }}</td>
                                </tr>
                            @endforeach
                        </tbody>

                    </table>
                    {{ $local_govt->links() }}

                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/add_suggestions.blade.php
<!-- First, extends to the CRUDBooster Layout -->
@extends('crudbooster::admin_template')
<script src="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/js/adminlte.min.js"></script>
{{-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/css/adminlte.min.css"> --}}

<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.7/css/fileinput.css" media="all" rel="stylesheet" type="text/css"/>
<style type="text/css">
    .main-section{
        margin:0 auto;
        padding: 20px;
        margin-top: 100px;
        background-color: #fff;
        box-shadow: 0px 0px 20px #c1c1c1;
    }
    .fileinput-remove,
    .fileinput-upload{
        display: none;
    }
</style>

@section('content')
  <!-- Your html goes here -->
  <div class='panel panel-default'>
    <div class='panel-heading'>Add Suggestion</div>
    <p>Give some suggestions to improve the system for the utter benefits of Nepali Citizens.</p>
    <div class='panel-body'>
        <form method='post' action='{{CRUDBooster::mainpath('add-save')}}' enctype="multipart/form-data">
            <div class='form-group'>
            <label>Name</label>
            <input type='text' name='name' required class='form-control'/>
            </div>
            <div class='form-group'>
                <label>Mobile</label>
                <input type='text' name='mobile' required class='form-control'/>
            </div>
            <div class='form-group'>
                <label>Suggestion</label>
                <textarea class="ckeditor form-control" name="description"></textarea>
            </div>
            <div class="file-loading">
                <input id="file-1" type="file" name="file" multiple class="file" data-overwrite-initial="false" data-min-file-count="1">
            </div>
            <!-- etc .... -->

        </form>
    </div>
    <div class='panel-footer'>
      <input type='submit' class='btn btn-primary' value='Save changes'/>
    </div>
  </div>

<script src="//cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
       $('.ckeditor').ckeditor();
    });
</script>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.7/js/fileinput.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.7/themes/fa/theme.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" type="text/javascript"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $("#file-1").fileinput({
        theme: 'fa',
        uploadUrl: "/image-view",
        uploadExtraData: function() {
            return {
                _token: $("input[name='_token']").val(),
            };
        },
        allowedFileExtensions: ['jpg', 'png', 'gif'],
        overwriteInitial: false,
        maxFileSize:2000,
        maxFilesNum: 10,
        slugCallback: function (filename) {
            return filename.replace('(', '_').replace(']', '_');
        }
    });
</script>

@endsection

resources/views/admin_dashboard.blade.php
@extends('crudbooster::admin_template')
@section('content')

    <div class="row">

        <div class="col-lg-2 col-xs-6">

            <div class="small-box bg-green">
                <div class="inner">
                    <h3>{{ $surveyed_local_govt_count }}</h3>
                    <p>complain</p>
                </div>
                <div class="icon">
                    <i class="ion ion-map"></i>
                </div>
                <a href={{ CRUDBooster::adminPath('active_local_govt') }} class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="col-lg-2 col-xs-6">

            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3>{{ $supervisors_count }}</h3>
                    <p>enquiry</p>
                </div>
                <div class="icon">
                    <i class="ion ion-person"></i>
                </div>
                <a href={{ CRUDBooster::adminPath('supervisors') }} class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="col-lg-2 col-xs-6">

            <div class="small-box bg-red">
                <div class="inner">
                    <h3>{{ $data_collectors }}</h3>
                    <p>request</p>
                </div>
                <div class="icon">
                    <i class="ion ion-person"></i>
                </div>
                <a href="{{ CRUDBooster::adminPath('data_collector') }}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="col-lg-2 col-xs-6">

            <div class="small-box bg-purple">
                <div class="inner">
                    <h3>{{ $collected_data }}</h3>
                    <p>suggestion</p>
                </div>
                <div class="icon">
                    <i class="ion ion-document"></i>
                </div>
                <a href="{{ route('get_submissions') }}" class="small-box-footer">Update data <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="col-lg-2 col-xs-6">

            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>{{ $collected_data }}</h3>
                    <p>complain & request</p>
                </div>
                <div class="icon">
                    <i class="ion ion-document"></i>
                </div>
                <a href="{{ route('get_submissions') }}" class="small-box-footer">Update data <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="col-lg-2 col-xs-6">

            <div class="small-box bg-primary">
                <div class="inner">
                    <h3>{{ $collected_data }}</h3>
                    <p>appreciation</p>
                </div>
                <div class="icon">
                    <i class="ion ion-document"></i>
                </div>
                <a href="{{ route('get_submissions') }}" class="small-box-footer">Update data <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Complaints</h3>
                </div>

                <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Complaints</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>

                        </tbody>

                    </table>
                    {{-- {{ $submissions_summary->links() }} --}}

                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>GHS</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{ asset('assets/img/favicon.png') }}" rel="icon">
  <link href="{{ asset('assets/img/apple-touch-icon.png') }}" rel="apple-touch-icon">

  <!-- Add icon library -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ asset('assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ asset('assets/vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
  <link href="{{ asset('assets/vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ asset('assets/vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
  <link href="{{ asset('assets/vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{ asset('assets/css/style_landing.css') }}" rel="stylesheet">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">

    <a href="/" class="logo"><img src="{{ asset('assets/images/logo.png') }}" alt="" class="img-fluid"></a>
      <h1 class="logo"><a href="/">{{ __('frontend.app_name') }}</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->

      <nav id="navbar" class="navbar">
        <ul>
            <li><a class="nav-link scrollto active" href="/">{{ __('frontend.home') }}</a></li>
            <li><a class="nav-link scrollto" href="#about">{{ __('frontend.faq') }}</a></li>
            <li><a class="nav-link scrollto" href="#">{{ __('frontend.privacy_policy') }}</a></li>
            <li><a class="nav-link scrollto " href="{{ route('suggestions.index') }}">{{ __('frontend.suggestion') }}</a></li>
            <li><a class="nav-link scrollto" href="#contacts">{{ __('frontend.contact') }}</a></li>
            <li><a class="getstarted scrollto" href="/admin">{{ __('frontend.login') }}</a></li>

            <li><a class="nav-link scrollto" href="#">
                <select class="changeLang">
                    <option value="ne" {{ session()->get('locale') == 'ne' ? 'selected' : '' }}>नेपाली</option>
                    <option value="en" {{ session()->get('locale') == 'en' ? 'selected' : '' }}>English</option>
                </select></a>
            </li>


        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">

    <div class="container">
        <div class="row">
          <div class="col-lg-6 pt-5 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center">
            <h1>{{ __('frontend.suggestion') }}</h1>
            <h2>{{ __('frontend.suggestion_text') }}
            </h2>
            <div class="d-flex">
              <a href="{{ route('suggestions.create') }}" class="btn-get-started scrollto"> {{ __('frontend.get started') }}</a>
            </div>
          </div>
          <div class="col-lg-6 order-1 order-lg-2 hero-img">
            <img src="{{ asset('assets/img/hero-img.png') }}" class="img-fluid animated" alt="">
          </div>
        </div>
    </div>

</section><!-- End Hero -->

  <main id="main">
    <div class="container">
        @yield('content')
    </div>

    <!-- ======= Contacts Section ======= -->
  <section id="contacts" class="testimonials section-bg">
    <div class="container">
        <div class="text-center">
            <h3>{{ __('frontend.contact') }} {{ __('frontend.details') }}</h3>
            <p>Et aut eum quis fuga eos sunt ipsa nihil. Labore corporis magni eligendi fuga maxime saepe commodi placeat.</p>
        </div>
    </div>
</section><!-- End Contacts Section -->

  </main>


  <!-- ======= Footer ======= -->
  <footer id="footer">
    {{-- <section id="contacts">
        <div class="footer-top">
            <div class="container">
            <div class="row  justify-content-center">
                <div class="col-lg-6">
                <h3>{{ __('frontend.contact') }} {{ __('frontend.details') }}</h3>
                <p>Et aut eum quis fuga eos sunt ipsa nihil. Labore corporis magni eligendi fuga maxime saepe commodi placeat.</p>
                </div>
            </div>
            </div>
        </div>
    </section> --}}

    <div class="container footer-bottom clearfix">
      <div class="copyright">
        &copy; Copyright <strong><span>eNno</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/enno-free-simple-bootstrap-template/ -->
        <!--Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> -->
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{{ asset('assets/vendor/purecounter/purecounter_vanilla.js') }}"></script>
<script src="{{ asset('assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/vendor/glightbox/js/glightbox.min.js') }}"></script>
<script src="{{ asset('assets/vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
<script src="{{ asset('assets/vendor/swiper/swiper-bundle.min.js') }}"></script>
<script src="{{ asset('assets/vendor/php-email-form/validate.js') }}"></script>

<!-- Template Main JS File -->
<script src="{{ asset('assets/js/main.js') }}"></script>

<script>
  var url = "{{ route('lan.change') }}";

  $('.changeLang').change(function(){
      window.location.href = url + "?lang=" + $(this).val();
  });
</script>

</body>

</html>

resources/views/supervisor_dashboard.blade.php
@extends('crudbooster::admin_template')
@section('content')
    {{-- <div class="row">
        <div class="col-xs-12">
            <div class="col-lg-6 col-xs-6">
                <h2>Supervisor Dashboard</h2>
            </div>
            <div class="col-lg-6 col-xs-6">
                <a href="{{ route('get_submissions') }}" class="btn btn-primary pull-right">
                    Reload Submissions <i class="fa fa-refresh" aria-hidden="true"></i>
                </a>
            </div>
        </div>
    </div> --}}

    <div class="row">

        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon bg-green"><i class="fa fa-map-marker"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Local Government</span>
                    <span class="info-box-number">{{ Session::get('local_government') }}</span>
                    <span class="info-box-text">{{ Session::get('district') }} , {{ Session::get('province') }}</span>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon bg-red"><i class="fa fa-users"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Data Collectors</span>
                    <span class="info-box-number">{{ $data_collectors_count }}</span>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon bg-aqua"><i class="fa fa-file-text-o"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Households</span>
                    <span class="info-box-number">{{ $data_count->count }}</span>
                </div>
            </div>
        </div>

        {{-- <div class="clearfix visible-sm-block"></div> --}}

        {{-- <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">New Members</span>
                    <span class="info-box-number">2,000</span>
                </div>
            </div>
        </div> --}}

    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Data Collectors List</h3>
                </div>

                <div class="box-body">
                    <table id="data_collectors" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Data Collector</th>
                                <th>Full Name</th>
                                <th>Email</th>
                                <th>Contact No.</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data_collectors as $row)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $row->username }}</td>
                                    <td>{{ $row->full_name }}</td>
                                    <td>{{ $row->email }}</td>
                                    <td>{{ $row->mobile }}</td>
                                </tr>
                            @endforeach
                        </tbody>

                    </table>
                    {{-- {{ $data_collectors->links() }} --}}

                </div>

            </div>
        </div>
    </div>
@endsection