routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\SuggestionController;
use App\Http\Controllers\SubmissionsController;
use App\Http\Controllers\ActiveLocalGovtController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/login', function () {
    header('Location:/admin');
    exit();
})->name('login');


Route::group(['prefix' => 'admin'], function () {
    Route::get('/get_submissions', [SubmissionsController::class, 'get_submissions'])->name('get_submissions');
    Route::get('/get_asset_data', [SubmissionsController::class, 'get_asset_data'])->name('get_asset_data');
    Route::get('/admin_dashboard', [DashboardController::class, 'admin_dashboard'])->name('admin_dashboard');
    Route::get('/supervisor_dashboard', [DashboardController::class, 'supervisor_dashboard'])->name('supervisor_dashboard');
    Route::get('/active_local_govt', [ActiveLocalGovtController::class, 'index'])->name('active_local_govt');

    // Route::get('/admin_dashboard', function () {
    //     return view('admin_dashboard');
    // });
    // Route::get('/supervisor_dashboard', function () {
    //     return view('supervisor_dashboard');
    // });
});

Route::resource('suggestions', SuggestionController::class);

Route::get('/', [LanguageController::class, 'index'])->name('home');
Route::get('lan-change', [LanguageController::class, 'langChange'])->name('lan.change');

app/Models/Suggestion.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Suggestion extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'mobile', 'suggestion', 'files'
    ];
}

app/Http/Controllers/SuggestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Suggestion;
use Illuminate\Http\Request;

class SuggestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $suggestions = Suggestion::latest()->paginate(5);

        return view('suggestions.index',compact('suggestions'))
        ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('suggestions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'mobile' => 'required',
            'suggestion' => 'required',
            'files' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        $input = $request->all();

        if ($file = $request->file('files')) {
            $destinationPath = 'uploads/';
            $profileImage = date('YmdHis') . "." . $file->getClientOriginalExtension();
            $file->move($destinationPath, $profileImage);
            $input['files'] = "$profileImage";
        }

        Suggestion::create($input);

        return redirect()->route('suggestions.index')
                        ->with('success','Suggestion created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Suggestion  $suggestion
     * @return \Illuminate\Http\Response
     */
    public function show(Suggestion $suggestion)
    {
        return view('suggestions.show',compact('suggestion'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Suggestion  $suggestion
     * @return \Illuminate\Http\Response
     */
    public function edit(Suggestion $suggestion)
    {
        return view('suggestions.edit',compact('suggestion'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Suggestion  $suggestion
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Suggestion $suggestion)
    {
        $request->validate([
            'name' => 'required',
            'mobile' => 'required',
            'suggestion' => 'required',
        ]);

        $input = $request->all();

        if ($file = $request->file('files')) {
            $destinationPath = 'uploads/';
            $profileImage = date('YmdHis') . "." . $file->getClientOriginalExtension();
            $file->move($destinationPath, $profileImage);
            $input['files'] = "$profileImage";
        }
        else{
            unset($input['files']);
        }

        $suggestion->update($input);

        return redirect()->route('suggestions.index')
                        ->with('success','Sugestion updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Suggestion  $suggestion
     * @return \Illuminate\Http\Response
     */
    public function destroy(Suggestion $suggestion)
    {

        $suggestion->delete();

        return redirect()->route('suggestions.index')
                        ->with('success','Suggestion deleted successfully');
    }
}

resources/views/suggestions/create.blade.php
@extends('layout')

@section('content')

<section id="services" class="services section-bg">
    <div class="container">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Suggestion</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('suggestions.index') }}"><i class="fa fa-arrow-left"></i> {{ __('frontend.back') }}</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="row">
<div class="col-lg-12 mt-5 mt-lg-0 d-flex align-items-stretch">

    <form action="{{ route('suggestions.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

         <div class="row">
                <div class="form-group col-md-6 mt-3 mt-md-0">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name">
                </div>
                <div class="form-group col-md-6 mt-3 mt-md-0">
                    <strong>Mobile Number:</strong>
                    <input type="text" class="form-control" name="mobile" placeholder="Mobile">
                </div>
                <div class="form-group">
                    <strong>Suggestion:</strong>
                    <textarea class="form-control" name="suggestion"></textarea>
                </div>
                <div class="form-group">
                    <strong>File:</strong>
                    <input type="file" name="files" class="form-control" placeholder="image">
                </div>
                {{-- <div class="text-center"><button type="submit">Submit</button></div> --}}
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary"><i class="fa fa-arrow-floppy-o"></i> {{ __('frontend.save') }}</button>
            </div>

        </div>

    </form>

  </div>
</div>
    </div>

</section>

  <script src="//cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
       $('.ckeditor').ckeditor();
    });
</script>

@endsection

resources/views/suggestions/edit.blade.php
@extends('layout')

@section('content')

<section id="services" class="services section-bg">
    <div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Suggestion</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('suggestions.index') }}"><i class="fa fa-arrow-left"></i>  {{ __('frontend.back') }}</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('suggestions.update',$suggestion->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')

         <div class="row">
            {{-- <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $suggestion->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Mobile:</strong>
                    <input type="text" class="form-control" name="mobile" placeholder="Mobile">
                </div>
            </div> --}}
            <div class="form-group col-md-6 mt-3 mt-md-0">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" value="{{ $suggestion->name }}">
            </div>
            <div class="form-group col-md-6 mt-3 mt-md-0">
                <strong>Mobile Number:</strong>
                <input type="text" class="form-control" name="mobile" value="{{ $suggestion->mobile }}">
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Suggestion:</strong>
                    <textarea class="form-control" name="suggestion">{{ $suggestion->suggestion }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>File:</strong>
                    <input type="file" name="files" class="form-control" placeholder="image">
                    <img src="/image/{{ $suggestion->files }}" width="300px">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
    </div>
</section>

<script src="//cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
       $('.ckeditor').ckeditor();
    });
</script>
@endsection

resources/views/suggestions/index.blade.php
@extends('layout')

@section('content')

<section id="services" class="services section-bg">
    <div class="container">

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>{{ __('frontend.suggestion') }}</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('suggestions.create') }}"><i class="fa fa-plus-circle"></i> {{ __('frontend.new') }}</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered table-striped table-hover table-condensed table-responsive">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Mobile</th>
            <th>Suggestion</th>
            <th>Files</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($suggestions as $suggestion)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $suggestion->name }}</td>
            <td>{{ $suggestion->mobile }}</td>
            <td>{{ $suggestion->suggestion }}</td>
            <td><img src="/image/{{ $suggestion->image }}" width="100px"></td>
            <td>
                <form action="{{ route('suggestions.destroy',$suggestion->id) }}" method="POST">

                    <a class="btn btn-info" href="{{ route('suggestions.show',$suggestion->id) }}"><i class="fa fa-eye"></i></a>

                    <a class="btn btn-primary" href="{{ route('suggestions.edit',$suggestion->id) }}"><i class="fa fa-pencil"></i></a>

                    @csrf
                    @method('DELETE')

                    <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>

    {!! $suggestions->links() !!}

    </div>
</section>

@endsection

resources/views/suggestions/show.blade.php
@extends('layout')

@section('content')

<section id="services" class="services section-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2> Show Suggestion</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('suggestions.index') }}"><i class="fa fa-arrow-left"></i>  {{ __('frontend.back') }}</a>
                </div>
            </div>
            <ul class="list-group">
                <li class="list-group-item"><strong>Name:</strong>
                    {{ $suggestion->name }}</li>
                <li class="list-group-item"><strong>Mobile:</strong>
                    {{ $suggestion->mobile }}</li>
                <li class="list-group-item"><strong>Suggestion:</strong>
                    {{ $suggestion->suggestion }}</li>
                <li class="list-group-item"><strong>Image:</strong>
                    <img src="/image/{{ $suggestion->image }}" width="500px"></li>
            </ul>
        </div>
    </div>

</section>

@endsection